import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const ui = readFileSync(new URL('../src/components/AdminExercises/ExerciseAuthoringWorkspace.tsx', import.meta.url), 'utf8');
const practice = readFileSync(new URL('../src/components/ExercisePractice/ExercisePractice.tsx', import.meta.url), 'utf8');
const app = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const reports = readFileSync(new URL('../src/components/ProblemReports/ProblemReportsDashboard.tsx', import.meta.url), 'utf8');
const service = readFileSync(new URL('../src/services/dayExerciseAuthoringService.ts', import.meta.url), 'utf8');
const rules = readFileSync(new URL('../../../firestore.rules', import.meta.url), 'utf8');

for (const label of ['Novo exercício', 'Editar exercício existente', 'Reconstruir este exercício', 'Criar lote de exercícios', 'Importar JSON', 'Copiar modelo de prompt para IA', 'Visualizar exercício', 'Salvar rascunho e fechar', 'Publicar', 'Cancelar', 'Voltar']) assert.match(ui, new RegExp(label));
for (const mode of ['append', 'insert_at', 'replace_day', 'replace_positions']) assert.match(ui + service, new RegExp(mode));
assert.match(ui, /Sandbox do exercício/);
assert.match(ui, /Voltar ao editor/);
assert.match(ui, /aria-label="Fechar sandbox"/);
assert.match(ui, /event\.key === 'Escape'/);
assert.match(ui, /window\.history\?\.pushState/);
assert.match(ui, /currentLanguage=\{language\} embedded/);
assert.match(readFileSync(new URL('../src/components/UI.tsx', import.meta.url), 'utf8'), /embedded \? 'relative h-/);
assert.match(ui, /Sem gravação de progresso, domínio, mastery ou conclusão/);
assert.match(reports, /Editar exercício existente/);
assert.match(reports, /Novo exercício/);
assert.doesNotMatch(reports, /AdminExerciseCreationModal/);
assert.match(reports, /builderInitial/);
assert.match(service, /runTransaction/);
assert.match(service, /transaction\.set\(publicRef/);
assert.match(service, /transaction\.delete\(draftRef/);
assert.match(service, /export async function listDaySequenceDrafts/);
assert.match(practice, /resolveAuthoredDayExercises/);
assert.match(app, /courseId=\{currentCourseId/);
assert.match(rules, /match \/publishedDayExerciseSequences/);
assert.match(rules, /allow read: if signedIn\(\)/);
assert.doesNotMatch(ui, /audioUrl.*<input/);
const sharedUi = readFileSync(new URL('../src/components/UI.tsx', import.meta.url), 'utf8');
assert.match(sharedUi, /repeatMicAvailable\(repeatPhase\)/);
assert.match(sharedUi, /Tentar ouvir novamente/);
assert.match(sharedUi, /result\.state === 'cancelled'/);
assert.match(ui, /contentOrder/);
assert.match(ui, /Texto para áudio\/TTS \(opcional\)/);
assert.match(ui, /Categoria\/modalidade visual/);
assert.doesNotMatch(service, /validatePublishedExerciseTypes/);
assert.match(sharedUi, /item\.instruction \|\| PL\.listenAndAnswer/);
assert.match(sharedUi, /item\.instruction \|\| PL\.listenAndRepeat/);
assert.match(sharedUi, /item\.contentOrder === 'display-first'/);
assert.match(sharedUi, /promptAudioText \? '' : 'hidden '/);
assert.match(ui, /Descartar as alterações não salvas/);
assert.match(ui, /Publicar como novo exercício/);
assert.match(ui, /Publicar substituindo e resolver relatório/);
assert.match(ui, /Rascunhos/);
assert.match(ui, /Localizar rascunhos/);
assert.match(reports, /intent: 'new'/);
assert.match(reports, /mode === 'replace-reported'/);
assert.match(ui, /normalizeReportedWorkbookId\(initial\.location\.workbook\.id\)/);
assert.match(ui, /Criando substituição para:/);
assert.match(ui, /Exercício original:/);
assert.match(ui, /Alterar localização/);
assert.match(ui, /disabled=\{locationLocked\}/);
assert.match(ui, /position: initial\.location\.exerciseIndex \+ 1/);
assert.match(ui, /closeAfterConfirmedOperation\(\)/);
assert.match(service, /resolveReportId/);
assert.match(service, /transaction\.update\(reportRef/);
assert.match(service, /status: 'resolved'/);
assert.match(reports, /resolvido na mesma transação/);

console.log('Exercise authoring UI and transactional wiring checks passed.');
