
import { PracticeItem } from './types';

// Future lessons can be generated by placing a PDF in the lessons/ folder.
// For example, if lesson3.pdf is added, the agent should read the PDF and generate lesson3
// using the same island structure and 100 point distribution.

// workbook number used in UI labels
export const WORKBOOK_NUMBER = 1;

const createItems = (lesson: number, track: number, items: Partial<PracticeItem>[]): PracticeItem[] => {
  const moduleType = `L${lesson}_I${track}`;
  return items.map((it, idx) => ({
    id: `${moduleType}-${idx}`,
    lessonId: lesson,
    moduleType: moduleType,
    type: it.type || 'writing',
    instruction: it.instruction || '',
    audioValue: it.audioValue || '',
    correctValue: it.correctValue || '',
    displayValue: it.displayValue,
    options: it.options,
    character: it.character,
    isNewVocab: it.isNewVocab
  }));
};
// TODO: future enhancement - automatically generate L{n}_TRACKS arrays by
// parsing a lesson PDF. The `createItems` helper keeps the format simple for
// scripts to emit. See similar tooling in the build scripts when working on
// Lesson 3 and beyond.

// --- Unit 1: The Alphabet and Numbers ---

const L1_TRACKS = [
  // Island 1: Alphabet Sound Groups (25 items)
  ...createItems(1, 1, [
    
    { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'A', options: ['H', 'B', 'F', 'L'], correctValue: 'H', isNewVocab: true },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'B', options: ['G', 'F', 'I', 'S'], correctValue: 'G' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'F', options: ['L', 'A', 'Q', 'O'], correctValue: 'L' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'I', options: ['Y', 'O', 'U', 'V'], correctValue: 'Y' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'U', options: ['W', 'M', 'N', 'Z'], correctValue: 'W' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'S', options: ['X', 'J', 'K', 'R'], correctValue: 'X' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'O', options: ['O', 'E', 'G', 'T'], correctValue: 'O' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'J', options: ['K', 'L', 'M', 'N'], correctValue: 'K' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'C', options: ['D', 'F', 'H', 'J'], correctValue: 'D' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'P', options: ['T', 'S', 'R', 'Q'], correctValue: 'T' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'V', options: ['E', 'A', 'I', 'O'], correctValue: 'E' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'M', options: ['N', 'P', 'Q', 'R'], correctValue: 'N' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'H', options: ['A', 'E', 'I', 'O'], correctValue: 'A' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'Y', options: ['I', 'E', 'A', 'U'], correctValue: 'I' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'Q', options: ['U', 'O', 'A', 'E'], correctValue: 'U' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'Z', options: ['X', 'Y', 'W', 'V'], correctValue: 'V' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'G', options: ['B', 'A', 'F', 'L'], correctValue: 'B' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'K', options: ['J', 'L', 'M', 'N'], correctValue: 'J' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'D', options: ['C', 'F', 'H', 'J'], correctValue: 'C' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'T', options: ['P', 'S', 'R', 'Q'], correctValue: 'P' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'E', options: ['V', 'A', 'I', 'O'], correctValue: 'V' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'N', options: ['M', 'P', 'Q', 'R'], correctValue: 'M' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'A', options: ['H', 'E', 'I', 'O'], correctValue: 'H' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'I', options: ['Y', 'E', 'A', 'U'], correctValue: 'Y' },
  { type: 'multiple-choice', instruction: 'Which letter has the same vowel sound?', audioValue: 'U', options: ['Q', 'O', 'A', 'E'], correctValue: 'Q' }
]),
  // Island 2: Numbers 0-10 Cardinal (15 items)
  ...createItems(1, 2, [
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Zero', options: ['0', '1', '6', '10'], correctValue: '0', isNewVocab: true },
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Three', options: ['2', '3', '7', '13'], correctValue: '3' },
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Eight', options: ['A', '8', 'H', '18'], correctValue: '8' },
    { type: 'writing', instruction: 'Type in words what you hear:', audioValue: 'One', correctValue: 'one' },
    { type: 'writing', instruction: 'Type in words what you hear:', audioValue: 'Two', correctValue: 'two' },
    { type: 'writing', instruction: 'Type in words what you hear:', audioValue: 'Five', correctValue: 'five' },
    { type: 'speaking', instruction: 'Pronounce correctly: Three', displayValue: '3', audioValue: 'Three', correctValue: 'three' },
    { type: 'speaking', instruction: 'Pronounce correctly: Eight', displayValue: '8', audioValue: 'Eight', correctValue: 'eight' },
    { type: 'writing', instruction: 'Math: What is two plus three?', displayValue: 'Math', audioValue: 'What is two plus three', correctValue: '5' },
    { type: 'writing', instruction: 'Type in words what you hear:', audioValue: 'Ten', correctValue: 'ten' },
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Four', options: ['4', '14', '40', '44'], correctValue: '4' },
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Six', options: ['6', '16', '60', '66'], correctValue: '6' },
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Seven', options: ['7', '17', '70', '77'], correctValue: '7' },
    { type: 'identification', instruction: 'Listen and pick the correct number:', audioValue: 'Nine', options: ['9', '19', '90', '99'], correctValue: '9' },
    { type: 'writing', instruction: 'Math: What is five plus five?', displayValue: 'Math', audioValue: 'What is five plus five', correctValue: '10' }
  ]),
  // Island 3: Numbers 11-20 Cardinal (15 items)
  ...createItems(1, 3, [
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Eleven', options: ['1', '11', '12', '21'], correctValue: '11', isNewVocab: true },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Twelve', options: ['2', '12', '20', '22'], correctValue: '12' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Thirteen', options: ['3', '13', '30', '33'], correctValue: '13' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Fifteen', options: ['5', '15', '50', '55'], correctValue: '15' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Twenty', options: ['12', '20', '2', '22'], correctValue: '20' },
    { type: 'writing', instruction: 'Math: What is ten plus five?', displayValue: 'Math', audioValue: 'What is ten plus five', correctValue: '15' },
    { type: 'multiple-choice', instruction: 'Review: Which letter has the same vocalic sound as that letter? /ei/', audioValue: 'H', options: ['A', 'B', 'C', 'D'], correctValue: 'A' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Fourteen', options: ['4', '14', '40', '44'], correctValue: '14' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Sixteen', options: ['6', '16', '60', '66'], correctValue: '16' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Seventeen', options: ['7', '17', '70', '77'], correctValue: '17' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Eighteen', options: ['8', '18', '80', '88'], correctValue: '18' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Nineteen', options: ['9', '19', '90', '99'], correctValue: '19' },
    { type: 'writing', instruction: 'Math: What is eleven plus nine?', displayValue: 'Math', audioValue: 'What is eleven plus nine', correctValue: '20' },
    { type: 'writing', instruction: 'Math: What is twelve plus one?', displayValue: 'Math', audioValue: 'What is twelve plus one', correctValue: '13' },
    { type: 'writing', instruction: 'Math: What is fifteen plus two?', displayValue: 'Math', audioValue: 'What is fifteen plus two', correctValue: '17' }
  ]),
  // Island 4: Basic Colors (10 items)
  ...createItems(1, 4, [
    { type: 'multiple-choice', instruction: 'Identify the color of the shirt:', displayValue: 'fa-shirt', audioValue: 'Green', options: ['Red', 'Blue', 'Green', 'Yellow'], correctValue: 'Green', isNewVocab: true },
    { type: 'multiple-choice', instruction: 'Identify the color of the car:', displayValue: 'fa-car', audioValue: 'Red', options: ['Red', 'Blue', 'Green', 'Black'], correctValue: 'Red' },
    { type: 'multiple-choice', instruction: 'Identify the color of the sky:', displayValue: 'fa-cloud-sun', audioValue: 'Blue', options: ['Red', 'Blue', 'Green', 'Black'], correctValue: 'Blue' },
    { type: 'identification', instruction: 'What color is it?', displayValue: 'fa-lemon', audioValue: 'Yellow', options: ['Yellow', 'Orange', 'Green', 'Blue'], correctValue: 'Yellow' },
    { type: 'multiple-choice', instruction: 'Identify the color of the grass:', displayValue: 'fa-leaf', audioValue: 'Green', options: ['Green', 'Red', 'Blue', 'Yellow'], correctValue: 'Green' },
    { type: 'multiple-choice', instruction: 'Identify the color of the apple:', displayValue: 'fa-apple-whole', audioValue: 'Red', options: ['Red', 'Green', 'Blue', 'Yellow'], correctValue: 'Red' },
    { type: 'multiple-choice', instruction: 'Identify the color of the ocean:', displayValue: 'fa-water', audioValue: 'Blue', options: ['Blue', 'Red', 'Green', 'Yellow'], correctValue: 'Blue' },
    { type: 'multiple-choice', instruction: 'Identify the color of the sun:', displayValue: 'fa-sun', audioValue: 'Yellow', options: ['Yellow', 'Red', 'Green', 'Blue'], correctValue: 'Yellow' },
    { type: 'writing', instruction: 'Type the color you hear:', audioValue: 'Red', correctValue: 'red' },
    { type: 'writing', instruction: 'Type the color you hear:', audioValue: 'Blue', correctValue: 'blue' }
  ]),
  // Island 5: Secondary Colors (10 items)
  ...createItems(1, 5, [
    { type: 'multiple-choice', instruction: 'Identify the color of the object:', displayValue: 'fa-carrot', audioValue: 'Orange', options: ['Orange', 'Yellow', 'Purple', 'White'], correctValue: 'Orange', isNewVocab: true },
    { type: 'multiple-choice', instruction: 'Identify the color of the phone:', displayValue: 'fa-mobile-screen', audioValue: 'Black', options: ['Black', 'White', 'Purple', 'Blue'], correctValue: 'Black' },
    { type: 'multiple-choice', instruction: 'Identify the color of the cloud:', displayValue: 'fa-cloud', audioValue: 'White', options: ['Black', 'White', 'Purple', 'Blue'], correctValue: 'White' },
    { type: 'multiple-choice', instruction: 'Identify the color of the glass:', displayValue: 'fa-wine-glass', audioValue: 'Purple', options: ['Purple', 'Blue', 'Red', 'Pink'], correctValue: 'Purple' },
    { type: 'multiple-choice', instruction: 'Identify the color of the coal:', displayValue: 'fa-cube', audioValue: 'Black', options: ['Black', 'White', 'Purple', 'Blue'], correctValue: 'Black' },
    { type: 'multiple-choice', instruction: 'Identify the color of the paper:', displayValue: 'fa-file', audioValue: 'White', options: ['Black', 'White', 'Purple', 'Blue'], correctValue: 'White' },
    { type: 'multiple-choice', instruction: 'Identify the color of the grape:', displayValue: 'fa-grapes', audioValue: 'Purple', options: ['Purple', 'Blue', 'Red', 'Pink'], correctValue: 'Purple' },
    { type: 'multiple-choice', instruction: 'Identify the color of the pumpkin:', displayValue: 'fa-ghost', audioValue: 'Orange', options: ['Orange', 'Yellow', 'Purple', 'White'], correctValue: 'Orange' },
    { type: 'writing', instruction: 'Type the color you hear:', audioValue: 'Black', correctValue: 'black' },
    { type: 'writing', instruction: 'Type the color you hear:', audioValue: 'White', correctValue: 'white' }
  ]),
  // Island 6: Math Practice (10 items)
  ...createItems(1, 6, [
    { type: 'writing', instruction: 'Math: What is four times two?', displayValue: 'Math', audioValue: 'What is four times two', correctValue: '8' },
    { type: 'writing', instruction: 'Math: What is ten divided by two?', displayValue: 'Math', audioValue: 'What is ten divided by two', correctValue: '5' },
    { type: 'speaking', instruction: 'Say the result: Eight', displayValue: '8', audioValue: 'Eight', correctValue: 'eight' },
    { type: 'writing', instruction: 'Math: What is three plus seven?', displayValue: 'Math', audioValue: 'What is three plus seven', correctValue: '10' },
    { type: 'writing', instruction: 'Math: What is twenty minus five?', displayValue: 'Math', audioValue: 'What is twenty minus five', correctValue: '15' },
    { type: 'writing', instruction: 'Math: What is six times two?', displayValue: 'Math', audioValue: 'What is six times two', correctValue: '12' },
    { type: 'writing', instruction: 'Math: What is nine divided by three?', displayValue: 'Math', audioValue: 'What is nine divided by three', correctValue: '3' },
    { type: 'writing', instruction: 'Math: What is fifteen plus five?', displayValue: 'Math', audioValue: 'What is fifteen plus five', correctValue: '20' },
    { type: 'writing', instruction: 'Math: What is twelve minus four?', displayValue: 'Math', audioValue: 'What is twelve minus four', correctValue: '8' },
    { type: 'writing', instruction: 'Math: What is five times three?', displayValue: 'Math', audioValue: 'What is five times three', correctValue: '15' }
  ]),
  // Island 7: Final Mastery (15 items)
  ...createItems(1, 7, [
    { type: 'multiple-choice', instruction: 'Which letter has the same vocalic sound as that letter? /ju:/', displayValue: 'Q', options: ['U', 'A', 'E', 'I'], correctValue: 'U' },
    { type: 'writing', instruction: 'Type in words what you hear:', audioValue: 'Nineteen', correctValue: 'nineteen' },
    { type: 'multiple-choice', instruction: 'Identify the color:', displayValue: 'fa-mobile-screen', audioValue: 'Black', options: ['Black', 'White', 'Purple', 'Blue'], correctValue: 'Black' },
    { type: 'speaking', instruction: 'Say the number:', audioValue: 'One hundred', correctValue: '100' },
    { type: 'multiple-choice', instruction: 'Which letter has the same vocalic sound as that letter? /ei/', audioValue: 'A', options: ['H', 'B', 'F', 'L'], correctValue: 'H' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Twelve', options: ['2', '12', '20', '22'], correctValue: '12' },
    { type: 'multiple-choice', instruction: 'Identify the color of the shirt:', displayValue: 'fa-shirt', audioValue: 'Green', options: ['Red', 'Blue', 'Green', 'Yellow'], correctValue: 'Green' },
    { type: 'writing', instruction: 'Math: What is ten plus ten?', displayValue: 'Math', audioValue: 'What is ten plus ten', correctValue: '20' },
    { type: 'speaking', instruction: 'Say the number:', audioValue: 'Thirteen', correctValue: '13' },
    { type: 'multiple-choice', instruction: 'Identify the color of the car:', displayValue: 'fa-car', audioValue: 'Red', options: ['Red', 'Blue', 'Green', 'Black'], correctValue: 'Red' },
    { type: 'writing', instruction: 'Type in words what you hear:', audioValue: 'Eleven', correctValue: 'eleven' },
    { type: 'identification', instruction: 'Listen and pick:', audioValue: 'Fifteen', options: ['5', '15', '50', '55'], correctValue: '15' },
    { type: 'multiple-choice', instruction: 'Identify the color of the sky:', displayValue: 'fa-cloud-sun', audioValue: 'Blue', options: ['Red', 'Blue', 'Green', 'Black'], correctValue: 'Blue' },
    { type: 'writing', instruction: 'Math: What is eight times two?', displayValue: 'Math', audioValue: 'What is eight times two', correctValue: '16' },
    { type: 'speaking', instruction: 'Say the number:', audioValue: 'Twenty', correctValue: '20' }
  ])
];

// Lesson 2: Vowels and Early Reader
const L2_TRACKS = [
  // Island 1 – Short vs Long Vowels (approx 25 items)
  ...createItems(2, 1, [
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'cat', options: ['/æ/','/e/','/aɪ/','/oʊ/'], correctValue: '/æ/', isNewVocab: true },
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'bed', options: ['/æ/','/e/','/ɪ/','/ʌ/'], correctValue: '/e/' },
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'bike', options: ['/aɪ/','/eɪ/','/oʊ/','/iː/'], correctValue: '/aɪ/' },
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'note', options: ['/ɒ/','/oʊ/','/uː/','/ə/'], correctValue: '/oʊ/' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "cake" short or long?', audioValue: 'cake', options: ['Short','Long'], correctValue: 'Long' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "cup" short or long?', audioValue: 'cup', options: ['Short','Long'], correctValue: 'Short' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "hat" short or long?', audioValue: 'hat', options: ['Short','Long'], correctValue: 'Short' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "me" short or long?', audioValue: 'me', options: ['Short','Long'], correctValue: 'Long' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "pot" short or long?', audioValue: 'pot', options: ['Short','Long'], correctValue: 'Short' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "rule" short or long?', audioValue: 'rule', options: ['Short','Long'], correctValue: 'Long' },
    { type: 'multiple-choice', instruction: 'Which sound is /æ/?', audioValue: 'cat', options: ['cat','cake','bike','note'], correctValue: 'cat' },
    { type: 'multiple-choice', instruction: 'Which sound is /e/?', audioValue: 'bed', options: ['bed','made','bite','not'], correctValue: 'bed' },
    { type: 'multiple-choice', instruction: 'Which sound is /aɪ/?', audioValue: 'bike', options: ['bit','bite','bet','bat'], correctValue: 'bite' },
    { type: 'multiple-choice', instruction: 'Which sound is /oʊ/?', audioValue: 'note', options: ['not','note','nut','net'], correctValue: 'note' },
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'sun', options: ['/ʌ/','/æ/','/iː/','/oʊ/'], correctValue: '/ʌ/' },
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'tree', options: ['/iː/','/eɪ/','/aɪ/','/uː/'], correctValue: '/iː/' },
    { type: 'multiple-choice', instruction: 'Listen and choose the vowel sound you hear.', audioValue: 'apple', options: ['/æ/','/e/','/aɪ/','/oʊ/'], correctValue: '/æ/' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "home" short or long?', audioValue: 'home', options: ['Short','Long'], correctValue: 'Long' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "log" short or long?', audioValue: 'log', options: ['Short','Long'], correctValue: 'Short' },
    { type: 'multiple-choice', instruction: 'Is the vowel in "cute" short or long?', audioValue: 'cute', options: ['Short','Long'], correctValue: 'Long' },
    { type: 'multiple-choice', instruction: 'Which sound is /ʌ/?', audioValue: 'cup', options: ['cup','cape','cop','cup'], correctValue: 'cup' },
    { type: 'multiple-choice', instruction: 'Which sound is /iː/?', audioValue: 'me', options: ['me','may','my','mow'], correctValue: 'me' },
    { type: 'multiple-choice', instruction: 'Which sound is /aɪ/?', audioValue: 'time', options: ['tie','take','tome','tom'], correctValue: 'tie' },
    { type: 'multiple-choice', instruction: 'Which sound is /oʊ/?', audioValue: 'road', options: ['rod','road','red','rid'], correctValue: 'road' }
  ]),
  // Island 2 – Letter Name vs Vowel Sound (dialogue style)
  ...createItems(2, 2, [
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "cat"?', audioValue: 'cat', options: ['/æ/','/e/','/aɪ/','/oʊ/'], correctValue: '/æ/', isNewVocab: true },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'A', options: ['A','E','I','O','U'], correctValue: 'A' },
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "bed"?', audioValue: 'bed', options: ['/æ/','/e/','/ɪ/','/ʌ/'], correctValue: '/e/' },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'E', options: ['A','E','I','O','U'], correctValue: 'E' },
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "bike"?', audioValue: 'bike', options: ['/aɪ/','/eɪ/','/oʊ/','/iː/'], correctValue: '/aɪ/' },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'I', options: ['A','E','I','O','U'], correctValue: 'I' },
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "note"?', audioValue: 'note', options: ['/oʊ/','/ɒ/','/uː/','/ə/'], correctValue: '/oʊ/' },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'O', options: ['A','E','I','O','U'], correctValue: 'O' },
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "sun"?', audioValue: 'sun', options: ['/ʌ/','/æ/','/iː/','/oʊ/'], correctValue: '/ʌ/' },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'U', options: ['A','E','I','O','U'], correctValue: 'U' },
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "apple"?', audioValue: 'apple', options: ['/æ/','/e/','/aɪ/','/oʊ/'], correctValue: '/æ/' },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'A', options: ['A','E','I','O','U'], correctValue: 'A' },
    { type: 'multiple-choice', instruction: 'Teacher: What vowel sound is in "tree"?', audioValue: 'tree', options: ['/iː/','/ɪ/','/eɪ/','/aɪ/'], correctValue: '/iː/' },
    { type: 'multiple-choice', instruction: 'Teacher: What is the letter name?', audioValue: 'E', options: ['A','E','I','O','U'], correctValue: 'E' }
  ]),
  // Island 3 – What is this? (picture recognition)
  ...createItems(2, 3, [
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-sun', audioValue: 'sun', options: ['sun','moon','star','cloud'], correctValue: 'sun', isNewVocab: true },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-shoe-prints', audioValue: 'toes', options: ['toes','fingers','nose','eyes'], correctValue: 'toes' },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-mountain', audioValue: 'rock', options: ['rock','stone','sand','water'], correctValue: 'rock' },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-tree', audioValue: 'tree', options: ['tree','bush','flower','grass'], correctValue: 'tree' },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-apple-whole', audioValue: 'apple', options: ['apple','orange','banana','grape'], correctValue: 'apple' },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-kite', audioValue: 'kite', options: ['kite','ball','plane','bird'], correctValue: 'kite' },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-orange', audioValue: 'orange', options: ['orange','apple','lemon','grape'], correctValue: 'orange' },
    { type: 'multiple-choice', instruction: 'What is this?', displayValue: 'fa-water', audioValue: 'water', options: ['water','juice','milk','soda'], correctValue: 'water' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'sun', audioValue: 'sun', correctValue: 'sun' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'toes', audioValue: 'toes', correctValue: 'toes' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'rock', audioValue: 'rock', correctValue: 'rock' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'apple', audioValue: 'apple', correctValue: 'apple' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'tree', audioValue: 'tree', correctValue: 'tree' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'kite', audioValue: 'kite', correctValue: 'kite' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'orange', audioValue: 'orange', correctValue: 'orange' },
    { type: 'writing', instruction: 'Spell the word you see:', displayValue: 'water', audioValue: 'water', correctValue: 'water' }
  ]),
  // Island 4 – Vowel identification in words
  ...createItems(2, 4, [
    { type: 'multiple-choice', instruction: 'What vowel is in "rock"?', audioValue: 'rock', options: ['A','E','I','O','U'], correctValue: 'O', isNewVocab: true },
    { type: 'multiple-choice', instruction:'What is the vowel sound in "kite"?', audioValue:'kite', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'What vowel is in "sun"?', audioValue:'sun', options:['A','E','I','O','U'], correctValue:'U' },
    { type: 'multiple-choice', instruction:'What is the vowel sound in "bed"?', audioValue:'bed', options:['Short','Long'], correctValue:'Short' },
    { type: 'multiple-choice', instruction:'What vowel is in "apple"?', audioValue:'apple', options:['A','E','I','O','U'], correctValue:'A' },
    { type: 'multiple-choice', instruction:'What is the vowel sound in "tree"?', audioValue:'tree', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'What vowel is in "home"?', audioValue:'home', options:['A','E','I','O','U'], correctValue:'O' },
    { type: 'multiple-choice', instruction:'What is the vowel sound in "log"?', audioValue:'log', options:['Short','Long'], correctValue:'Short' },
    { type: 'multiple-choice', instruction:'What vowel is in "cake"?', audioValue:'cake', options:['A','E','I','O','U'], correctValue:'A' },
    { type: 'multiple-choice', instruction:'What is the vowel sound in "cute"?', audioValue:'cute', options:['Short','Long'], correctValue:'Long' }
  ]),
  // Island 5 – Articles practice
  ...createItems(2, 5, [
    { type: 'multiple-choice', instruction:'It is ___ apple', options:['a','an'], correctValue:'an', audioValue:'apple', isNewVocab:true },
    { type: 'multiple-choice', instruction:'It is ___ kite', options:['a','an'], correctValue:'a', audioValue:'kite' },
    { type: 'multiple-choice', instruction:'He has ___ orange', options:['a','an'], correctValue:'an', audioValue:'orange' },
    { type: 'multiple-choice', instruction:'She sees ___ sun', options:['a','an'], correctValue:'a', audioValue:'sun' },
    { type: 'multiple-choice', instruction:'We read ___ book', options:['a','an'], correctValue:'a', audioValue:'book' },
    { type: 'multiple-choice', instruction:'I eat ___ apple', options:['a','an'], correctValue:'an', audioValue:'apple' },
    { type: 'multiple-choice', instruction:'They fly ___ kite', options:['a','an'], correctValue:'a', audioValue:'kite' },
    { type: 'multiple-choice', instruction:'He found ___ rock', options:['a','an'], correctValue:'a', audioValue:'rock' },
    { type: 'multiple-choice', instruction:'She wears ___ hat', options:['a','an'], correctValue:'a', audioValue:'hat' },
    { type: 'multiple-choice', instruction:'It is ___ orange in the box', options:['a','an'], correctValue:'an', audioValue:'orange' }
  ]),
  // Island 6 – Reading comprehension and dialogue
  ...createItems(2, 6, [
    { type: 'multiple-choice', instruction:'Read the passage below before answering the questions.', displayValue:'A Day in Nature\nThe sun is shining. A boy plays with a kite near a tree. He eats an apple and drinks water. He steps on a rock and wiggles his toes in the grass.', options:['I read the text'], correctValue:'I read the text' },
    { type: 'multiple-choice', instruction:'Is it a sunny day?', options:['Yes','No'], correctValue:'Yes' },
    { type: 'multiple-choice', instruction:'What color is the kite?', options:['red','blue','green','yellow'], correctValue:'blue' },
    { type: 'multiple-choice', instruction:'Where is the boy?', options:['in a tree','on a rock','near a tree','under a rock'], correctValue:'near a tree' },
    { type: 'multiple-choice', instruction:'Is the fruit an orange?', options:['Yes','No'], correctValue:'No' },
    { type: 'multiple-choice', instruction:'Teacher: What is the weather like?', options:['It is sunny.','It is rainy.','It is snowy.','It is windy.'], correctValue:'It is sunny.' },
    { type: 'multiple-choice', instruction:'Teacher: What does he eat?', options:['He eats a banana.','He eats an apple.','He eats a sandwich.','He eats an orange.'], correctValue:'He eats an apple.' },
    { type: 'multiple-choice', instruction:'Teacher: What does he drink?', options:['He drinks juice.','He drinks water.','He drinks milk.','He drinks soda.'], correctValue:'He drinks water.' }
  ]),
  // Island 7: Final mastery exercises (15 items)
  ...createItems(2, 7, [
    { type: 'multiple-choice', instruction:'Which vowel is in "cat"?', audioValue:'cat', options:['A','E','I','O','U'], correctValue:'A' },
    { type: 'multiple-choice', instruction:'Is the vowel in "cake" short or long?', audioValue:'cake', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'Which vowel is in "bed"?', audioValue:'bed', options:['A','E','I','O','U'], correctValue:'E' },
    { type: 'multiple-choice', instruction:'Is the vowel sound short or long?', audioValue:'he', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'Which vowel is in "sit"?', audioValue:'sit', options:['A','E','I','O','U'], correctValue:'I' },
    { type: 'multiple-choice', instruction:'Is the vowel in "bike" short or long?', audioValue:'bike', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'Which vowel is in "hot"?', audioValue:'hot', options:['A','E','I','O','U'], correctValue:'O' },
    { type: 'multiple-choice', instruction:'Is the vowel sound short or long?', audioValue:'note', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'Which vowel is in "cup"?', audioValue:'cup', options:['A','E','I','O','U'], correctValue:'U' },
    { type: 'multiple-choice', instruction:'Is the vowel in "cute" short or long?', audioValue:'cute', options:['Short','Long'], correctValue:'Long' },
    { type: 'multiple-choice', instruction:'Which vowel is in "tree"?', audioValue:'tree', options:['A','E','I','O','U'], correctValue:'E' },
    { type: 'multiple-choice', instruction:'Is the vowel in "pig" short or long?', audioValue:'pig', options:['Short','Long'], correctValue:'Short' },
    { type: 'multiple-choice', instruction:'Which vowel is in "home"?', audioValue:'home', options:['A','E','I','O','U'], correctValue:'O' },
    { type: 'multiple-choice', instruction:'Is the vowel sound short or long?', audioValue:'rule', options:['Short','Long'], correctValue:'Long' },
    { type: 'speaking', instruction:'Pronounce correctly: cat', displayValue:'cat', audioValue:'cat', correctValue:'cat' }
  ])
];

export const PRACTICE_ITEMS: PracticeItem[] = [
  ...L1_TRACKS, ...L2_TRACKS
];

export const MODULE_NAMES: Record<string, string> = {
  'L1_I1': 'The Alphabet groups',
  'L1_I2': 'Numbers 0-10 Cardinal',
  'L1_I3': 'Numbers 11-20 Cardinal',
  'L1_I4': 'Basic Colors',
  'L1_I5': 'Secondary Colors',
  'L1_I6': 'Math Practice',
  'L1_I7': 'Unit 1 Mastery',
  'L2_I1': 'Short vs Long Vowels',
  'L2_I2': 'Letter vs Sound Dialogue',
  'L2_I3': 'Picture Vocabulary',
  'L2_I4': 'Vowel Identification',
  'L2_I5': 'Articles a/an',
  'L2_I6': 'Reading & Dialogue',
  'L2_I7': 'Unit 2 Mastery'
};

export const MODULE_ICONS: Record<string, string> = {
  'L1_I1': 'fa-font',
  'L1_I2': 'fa-list-ol',
  'L1_I3': 'fa-sort-numeric-up',
  'L1_I4': 'fa-palette',
  'L1_I5': 'fa-palette',
  'L1_I6': 'fa-calculator',
  'L1_I7': 'fa-award',
  'L2_I1': 'fa-volume-up',
  'L2_I2': 'fa-comments',
  'L2_I3': 'fa-image',
  'L2_I4': 'fa-search',
  'L2_I5': 'fa-file-alt',
  'L2_I6': 'fa-book-open',
  'L2_I7': 'fa-award'
};

export const GRAMMAR_GUIDES: Record<string, string[]> = {
  'L1_I1': [
    'Phonetic Families: Patterns in English sounds help us hear letters correctly.',
    'Group /i:/: B, C, D, E, G, P, T, V.',
    'Group /ei/: A, H, J, K.'
  ],
  'L1_I2': [
    'Cardinal Numbers: Used for counting (0, 1, 2, 3...).',
    'Careful with Three (3) vs Tree and Eight (8) vs H!'
  ],
  'L1_I3': [
    'Cardinal Numbers 11-20: Focus on the "teen" endings (13-19).',
    'Review letters alongside numbers to master A1 basics.'
  ],
  'L1_I4': ['Colors describe objects.', 'Identify colors without visual aids for better mastery.'],
  'L1_I5': ['Expand your vocabulary with adjectives and objects.', 'Focus on recalling the name of the color.'],
  'L2_I1': ['Practice listening: short vs long vowel sounds.', 'Match words like cat /æ/ and cake /eɪ/.'],
  'L2_I2': ['Answer teacher questions about vowel sounds and letter names.', 'Pairs of questions reinforce both skills.'],
  'L2_I3': ['Recognize vocabulary pictures: sun, toes, rock, tree, apple, kite, orange, water.', 'Spell the words you see.'],
  'L2_I4': ['Name the vowel in a word or say if it is short/long.', 'Focus on words from the lesson.'],
  'L2_I5': ['Choose “a” or “an” in simple sentences.', 'Articles before words beginning with vowel sounds.'],
  'L2_I6': ['Read a short passage and answer questions.', 'Practice simple dialogue responses.'],
  'L2_I7': ['Final mastery of Unit 2.', 'Apply all learned skills.']
};

export const LESSON_CONFIGS = Array.from({ length: 12 }, (_, i) => ({
  id: i + 1,
  title: i === 0 ? "The Alphabet and Numbers" : i === 1 ? "The Five Vowels" : `Lesson ${i + 1}`,
  modules: Array.from({ length: 7 }, (_, j) => `L${i+1}_I${j+1}`)
}));
