import { Exercise, Lesson } from '../../types';
import { lesson1 as englishLesson1 } from '../../data/workbook1/lesson1';
import { lesson2 as englishLesson2 } from '../../data/workbook1/lesson2';
import { lesson3 as englishLesson3 } from '../../data/workbook1/lesson3';
import { lesson4 as englishLesson4 } from '../../data/workbook1/lesson4';
import { lesson5 as englishLesson5 } from '../../data/workbook1/lesson5';

type LanguageKey = 'pt' | 'es' | 'el' | 'he';

interface LanguagePack {
  workbookId: string;
  workbookTitle: string;
  lessonTitles: string[];
  replacements: Array<[string, string]>;
}

// English files are the authoritative source. When a new lesson is added or
// corrected in English, add it here and extend every language pack's lessonTitles
// and replacements accordingly (mirrored multilingual workflow).
const BASE_LESSONS: Lesson[] = [englishLesson1, englishLesson2, englishLesson3, englishLesson4, englishLesson5];

const languagePacks: Record<LanguageKey, LanguagePack> = {
  pt: {
    workbookId: 'pt_wb1',
    workbookTitle: 'Workbook 1 de Portugues',
    lessonTitles: [
      'Licao 1: Alfabeto e Numeros',
      'Licao 2: Vogais e Leitura Inicial',
      'Licao 3: Rotina Diaria e Atividades',
      'Licao 4: Placeholder',
      'Licao 5: Placeholder',
    ],
    replacements: [
      // ── Lesson 1: alphabet & number instructions ─────────────────────────
      ['What are you listening to?', 'O que voce esta ouvindo?'],
      ['Listen and tap the correct color.', 'Escute e toque na cor correta.'],
      ['Listen and pick the correct letter.', 'Escute e escolha a letra correta.'],
      ['Listen and pick the correct number.', 'Escute e escolha o numero correto.'],
      ['Listen and repeat exactly as you hear.', 'Escute e repita exatamente como voce ouve.'],
      ['What color is it? Answer in a full sentence.', 'Qual e a cor? Responda com uma frase completa.'],
      ['What color is it?', 'Qual e a cor?'],
      ['Answer in a full sentence.', 'Responda com uma frase completa.'],
      ['The teacher asks: ', 'O professor pergunta: '],
      ['The teacher says: ', 'O professor diz: '],
      [' — Choose the correct response.', ' — Escolha a resposta correta.'],
      ['Type in words what you hear.', 'Escreva por extenso o que voce ouvir.'],
      // ── Lesson 2: vowels & reading instructions ───────────────────────────
      ['Listen and pick the correct word.', 'Escute e escolha a palavra correta.'],
      ['Teacher: What vowel letter is in ', 'Professor: Qual letra vogal esta em '],
      ['Teacher: What is the letter name?', 'Professor: Qual e o nome da letra?'],
      ['Is the vowel in ', 'A vogal em '],
      ['" short or long?', '" e curta ou longa?'],
      // ── Lesson 3: daily routines instructions ─────────────────────────────
      ['Listen and pick the correct answer.', 'Escute e escolha a resposta correta.'],
      ['Listen: ', 'Escute: '],
      ['What does Daniel do in the morning?', 'O que Daniel faz de manha?'],
      ['What does Sarah do before breakfast?', 'O que Sarah faz antes do cafe da manha?'],
      ['What does Tom do with his breakfast?', 'O que Tom faz com o cafe da manha?'],
      ['What does Lisa do before school?', 'O que Lisa faz antes da escola?'],
      ['What does Mark do to go to school?', 'Como Mark vai para a escola?'],
      ['Which shows what you do at school?', 'Qual mostra o que voce faz na escola?'],
      ['Which shows what you do in the afternoon?', 'Qual mostra o que voce faz a tarde?'],
      ['Which shows what you do before bed?', 'Qual mostra o que voce faz antes de dormir?'],
      ['What do you do before sleeping?', 'O que voce faz antes de dormir?'],
      // ── General / originally present ──────────────────────────────────────
      ['Lesson ', 'Licao '],
      ['Which letter has the same vowel sound?', 'Qual letra tem o mesmo som vocalico?'],
      ['Listen and pick the correct number:', 'Escute e escolha o numero correto:'],
      ['Type in words what you hear:', 'Escreva por extenso o que voce ouvir:'],
      ['Math: What is ', 'Matematica: Quanto e '],
      ['Identify the color of the', 'Identifique a cor do'],
      ['Identify the color:', 'Identifique a cor:'],
      ['Type the color you hear:', 'Escreva a cor que voce ouvir:'],
      ['Pronounce correctly:', 'Pronuncie corretamente:'],
      ['Say the number:', 'Diga o numero:'],
      ['Say the result:', 'Diga o resultado:'],
      ['What does', 'O que'],
      ['What is this?', 'O que e isto?'],
      ['Write what you hear:', 'Escreva o que voce ouvir:'],
      ['Say:', 'Diga:'],
      ['Repeat:', 'Repita:'],
      ['Read and repeat:', 'Leia e repita:'],
      ['Read and write:', 'Leia e escreva:'],
      ['Listen and answer:', 'Escute e responda:'],
      ['Daily Routines and Activities', 'Rotina Diaria e Atividades'],
      ['wake up', 'acordar'],
      ['take a shower', 'tomar banho'],
      ['eat breakfast', 'tomar cafe da manha'],
      ['get ready for school', 'preparar-se para a escola'],
      ['walk to school', 'ir a pe para a escola'],
      ['study', 'estudar'],
      ['have lunch', 'almocar'],
      ['go to bed', 'ir para a cama'],
      ['brush your teeth', 'escovar os dentes'],
      ['homework', 'dever de casa'],
      ['television', 'televisao'],
      ['breakfast', 'cafe da manha'],
      ['school', 'escola'],
      ['play', 'brincar'],
      ['shower', 'banho'],
      ['water', 'agua'],
      ['tree', 'arvore'],
      ['rock', 'pedra'],
      ['kite', 'pipa'],
      ['sun', 'sol'],
      ['apple', 'maca'],
      ['orange', 'laranja'],
      ['toes', 'dedos do pe'],
      ['Zero', 'zero'],
      ['One', 'um'],
      ['Two', 'dois'],
      ['Three', 'tres'],
      ['Four', 'quatro'],
      ['Five', 'cinco'],
      ['Six', 'seis'],
      ['Seven', 'sete'],
      ['Eight', 'oito'],
      ['Nine', 'nove'],
      ['Ten', 'dez'],
      ['Eleven', 'onze'],
      ['Twelve', 'doze'],
      ['Thirteen', 'treze'],
      ['Fourteen', 'quatorze'],
      ['Fifteen', 'quinze'],
      ['Sixteen', 'dezesseis'],
      ['Seventeen', 'dezessete'],
      ['Eighteen', 'dezoito'],
      ['Nineteen', 'dezenove'],
      ['Twenty', 'vinte'],
      ['Red', 'vermelho'],
      ['Blue', 'azul'],
      ['Green', 'verde'],
      ['Yellow', 'amarelo'],
      ['Orange', 'laranja'],
      ['Purple', 'roxo'],
      ['Black', 'preto'],
      ['White', 'branco'],
      ['Long', 'Longa'],
      ['Short', 'Curta'],
    ],
  },
  es: {
    workbookId: 'es_wb1',
    workbookTitle: 'Workbook 1 de Espanol',
    lessonTitles: [
      'Leccion 1: Alfabeto y Numeros',
      'Leccion 2: Vocales y Lectura Inicial',
      'Leccion 3: Rutinas Diarias y Actividades',
      'Leccion 4: Placeholder',
      'Leccion 5: Placeholder',
    ],
    replacements: [
      // ── Lesson 1: alphabet & number instructions ─────────────────────────
      ['What are you listening to?', 'Que estas escuchando?'],
      ['Listen and tap the correct color.', 'Escucha y toca el color correcto.'],
      ['Listen and pick the correct letter.', 'Escucha y elige la letra correcta.'],
      ['Listen and pick the correct number.', 'Escucha y elige el numero correcto.'],
      ['Listen and repeat exactly as you hear.', 'Escucha y repite exactamente lo que oyes.'],
      ['What color is it? Answer in a full sentence.', 'De que color es? Responde con una oracion completa.'],
      ['What color is it?', 'De que color es?'],
      ['Answer in a full sentence.', 'Responde con una oracion completa.'],
      ['The teacher asks: ', 'El profesor pregunta: '],
      ['The teacher says: ', 'El profesor dice: '],
      [' — Choose the correct response.', ' — Elige la respuesta correcta.'],
      ['Type in words what you hear.', 'Escribe con palabras lo que oyes.'],
      // ── Lesson 2: vowels & reading instructions ───────────────────────────
      ['Listen and pick the correct word.', 'Escucha y elige la palabra correcta.'],
      ['Teacher: What vowel letter is in ', 'Profesor: Que letra vocal esta en '],
      ['Teacher: What is the letter name?', 'Profesor: Cual es el nombre de la letra?'],
      ['Is the vowel in ', 'La vocal en '],
      ['" short or long?', '" es corta o larga?'],
      // ── Lesson 3: daily routines instructions ─────────────────────────────
      ['Listen and pick the correct answer.', 'Escucha y elige la respuesta correcta.'],
      ['Listen: ', 'Escucha: '],
      ['What does Daniel do in the morning?', 'Que hace Daniel en la manana?'],
      ['What does Sarah do before breakfast?', 'Que hace Sarah antes del desayuno?'],
      ['What does Tom do with his breakfast?', 'Que hace Tom con su desayuno?'],
      ['What does Lisa do before school?', 'Que hace Lisa antes de la escuela?'],
      ['What does Mark do to go to school?', 'Como va Mark a la escuela?'],
      ['Which shows what you do at school?', 'Cual muestra lo que haces en la escuela?'],
      ['Which shows what you do in the afternoon?', 'Cual muestra lo que haces por la tarde?'],
      ['Which shows what you do before bed?', 'Cual muestra lo que haces antes de acostarse?'],
      ['What do you do before sleeping?', 'Que haces antes de acostarte?'],
      // ── General / originally present ──────────────────────────────────────
      ['Lesson ', 'Leccion '],
      ['Which letter has the same vowel sound?', 'Que letra tiene el mismo sonido vocalico?'],
      ['Listen and pick the correct number:', 'Escucha y elige el numero correcto:'],
      ['Type in words what you hear:', 'Escribe con palabras lo que oyes:'],
      ['Math: What is ', 'Matematicas: Cuanto es '],
      ['Identify the color of the', 'Identifica el color del'],
      ['Identify the color:', 'Identifica el color:'],
      ['Type the color you hear:', 'Escribe el color que oyes:'],
      ['Pronounce correctly:', 'Pronuncia correctamente:'],
      ['What is this?', 'Que es esto?'],
      ['Write what you hear:', 'Escribe lo que oyes:'],
      ['Say:', 'Di:'],
      ['Repeat:', 'Repite:'],
      ['Read and repeat:', 'Lee y repite:'],
      ['Read and write:', 'Lee y escribe:'],
      ['Listen and answer:', 'Escucha y responde:'],
      ['Daily Routines and Activities', 'Rutinas Diarias y Actividades'],
      ['wake up', 'despertarse'],
      ['take a shower', 'ducharse'],
      ['eat breakfast', 'desayunar'],
      ['get ready for school', 'prepararse para la escuela'],
      ['walk to school', 'caminar a la escuela'],
      ['study', 'estudiar'],
      ['have lunch', 'almorzar'],
      ['go to bed', 'acostarse'],
      ['brush your teeth', 'cepillarse los dientes'],
      ['homework', 'tarea'],
      ['television', 'television'],
      ['breakfast', 'desayuno'],
      ['school', 'escuela'],
      ['play', 'jugar'],
      ['shower', 'ducha'],
      ['water', 'agua'],
      ['tree', 'arbol'],
      ['rock', 'roca'],
      ['kite', 'cometa'],
      ['sun', 'sol'],
      ['apple', 'manzana'],
      ['orange', 'naranja'],
      ['toes', 'dedos del pie'],
      ['Zero', 'cero'],
      ['One', 'uno'],
      ['Two', 'dos'],
      ['Three', 'tres'],
      ['Four', 'cuatro'],
      ['Five', 'cinco'],
      ['Six', 'seis'],
      ['Seven', 'siete'],
      ['Eight', 'ocho'],
      ['Nine', 'nueve'],
      ['Ten', 'diez'],
      ['Eleven', 'once'],
      ['Twelve', 'doce'],
      ['Thirteen', 'trece'],
      ['Fourteen', 'catorce'],
      ['Fifteen', 'quince'],
      ['Sixteen', 'dieciseis'],
      ['Seventeen', 'diecisiete'],
      ['Eighteen', 'dieciocho'],
      ['Nineteen', 'diecinueve'],
      ['Twenty', 'veinte'],
      ['Red', 'rojo'],
      ['Blue', 'azul'],
      ['Green', 'verde'],
      ['Yellow', 'amarillo'],
      ['Orange', 'naranja'],
      ['Purple', 'morado'],
      ['Black', 'negro'],
      ['White', 'blanco'],
      ['Long', 'Larga'],
      ['Short', 'Corta'],
    ],
  },
  el: {
    workbookId: 'el_wb1',
    workbookTitle: 'Greek Workbook 1',
    lessonTitles: [
      'Mathima 1: Alfavito kai Arithmoi',
      'Mathima 2: Fonienta kai Proti Anagnosi',
      'Mathima 3: Kathimerines Routines kai Drastiriotites',      'Mathima 4: Placeholder',
      'Mathima 5: Placeholder',    ],
    replacements: [
      ['Lesson ', 'Mathima '],
      ['Which letter has the same vowel sound?', 'Poio gramma exei ton idio fthinoggo?'],
      ['Listen and pick the correct number:', 'Akouse kai dialexe ton sosto arithmo:'],
      ['Type in words what you hear:', 'Grapse me lexeis auto pou akous:'],
      ['What is this?', 'Ti einai auto?'],
      ['Write what you hear:', 'Grapse auto pou akous:'],
      ['Say:', 'Pes:'],
      ['Repeat:', 'Epanalave:'],
      ['Read and repeat:', 'Diavase kai epanalave:'],
      ['Listen and answer:', 'Akouse kai apantise:'],
      ['Daily Routines and Activities', 'Kathimerines Routines kai Drastiriotites'],
      ['wake up', 'xypnao'],
      ['take a shower', 'kano ntous'],
      ['eat breakfast', 'troo proino'],
      ['get ready for school', 'etoimazomai gia to scholeio'],
      ['walk to school', 'pao me ta podia sto scholeio'],
      ['study', 'meletao'],
      ['have lunch', 'troo mesimeriano'],
      ['go to bed', 'pao sto krevati'],
      ['brush your teeth', 'vourtsizo ta dontia mou'],
      ['homework', 'ergasia gia to spiti'],
      ['television', 'tileorasi'],
      ['breakfast', 'proino'],
      ['school', 'scholeio'],
      ['play', 'paizo'],
      ['water', 'nero'],
      ['tree', 'dentro'],
      ['rock', 'petra'],
      ['kite', 'aetos'],
      ['sun', 'ilios'],
      ['apple', 'milo'],
      ['orange', 'portokali'],
      ['Red', 'kokkino'],
      ['Blue', 'ble'],
      ['Green', 'prasimo'],
      ['Yellow', 'kitrino'],
      ['Black', 'mavro'],
      ['White', 'lefko'],
    ],
  },
  he: {
    workbookId: 'he_wb1',
    workbookTitle: 'Hebrew Workbook 1',
    lessonTitles: [
      'Shiur 1: Alefbet VeMisparim',
      'Shiur 2: Tnuot VeKriah Rishonit',
      'Shiur 3: Seder Yom VePeulot',
      'Shiur 4: Placeholder',
      'Shiur 5: Placeholder',
    ],
    replacements: [
      ['Lesson ', 'Shiur '],
      ['Which letter has the same vowel sound?', 'Eizo otiyot im oto tzelel tnua?'],
      ['Listen and pick the correct number:', 'Hakshiv vevchar et hamispar hanachon:'],
      ['Type in words what you hear:', 'Kteov bemilim ma sheata shomea:'],
      ['What is this?', 'Ma ze?'],
      ['Write what you hear:', 'Kteov ma sheata shomea:'],
      ['Say:', 'Emor:'],
      ['Repeat:', 'Chazor:'],
      ['Read and repeat:', 'Kra vechazor:'],
      ['Listen and answer:', 'Hakshiv veane:'],
      ['Daily Routines and Activities', 'Seder Yom VePeulot'],
      ['wake up', 'mitorer'],
      ['take a shower', 'mitkaleach'],
      ['eat breakfast', 'ochel aruchat boker'],
      ['get ready for school', 'mitkonen lebeit sefer'],
      ['walk to school', 'holech lveit sefer'],
      ['study', 'lomed'],
      ['have lunch', 'ochel tzohorayim'],
      ['go to bed', 'holech lishon'],
      ['brush your teeth', 'tzocheach shinayim'],
      ['homework', 'shiurei bayit'],
      ['television', 'televizya'],
      ['breakfast', 'aruchat boker'],
      ['school', 'beit sefer'],
      ['play', 'mesachek'],
      ['water', 'mayim'],
      ['tree', 'etz'],
      ['rock', 'even'],
      ['kite', 'afifon'],
      ['sun', 'shemesh'],
      ['apple', 'tapuach'],
      ['orange', 'tapuz'],
      ['Red', 'adom'],
      ['Blue', 'kachol'],
      ['Green', 'yarok'],
      ['Yellow', 'tzahov'],
      ['Black', 'shachor'],
      ['White', 'lavan'],
    ],
  },
};

function replaceText(value: string | undefined, replacements: Array<[string, string]>): string | undefined {
  if (!value) return value;
  let nextValue = value;
  for (const [from, to] of replacements) {
    nextValue = nextValue.split(from).join(to);
  }
  return nextValue;
}

function transformExercise(exercise: Exercise, replacements: Array<[string, string]>): Exercise {
  return {
    ...exercise,
    instruction: replaceText(exercise.instruction, replacements) || exercise.instruction,
    displayValue: replaceText(exercise.displayValue, replacements),
    audioValue: replaceText(exercise.audioValue, replacements) || exercise.audioValue,
    correctValue: replaceText(exercise.correctValue, replacements) || exercise.correctValue,
    options: exercise.options?.map((option) => replaceText(option, replacements) || option),
  };
}

// Prefix lesson/day/exercise IDs with the language code so that progress keys
// (stored in the Firestore `days` map) are unique per course.  English lessons
// use their original IDs (wb1_l1_d1), PT/ES/etc. get e.g. pt_wb1_l1_d1.
function transformLesson(lesson: Lesson, title: string, langKey: LanguageKey, replacements: Array<[string, string]>): Lesson {
  const prefix = `${langKey}_`;
  return {
    ...lesson,
    id: `${prefix}${lesson.id}`,
    title,
    days: lesson.days.map((day) => ({
      ...day,
      id: `${prefix}${day.id}`,
      exercises: day.exercises.map((exercise) => ({
        ...transformExercise(exercise, replacements),
        id: `${prefix}${exercise.id}`,
      })),
    })),
  };
}

export function buildReplicatedWorkbook1(language: LanguageKey) {
  const pack = languagePacks[language];

  return {
    id: pack.workbookId,
    title: pack.workbookTitle,
    lessons: BASE_LESSONS.map((lesson, index) =>
      transformLesson(lesson, pack.lessonTitles[index], language, pack.replacements),
    ),
  };
}
